scripts added for pull-request
pro100Daim/git_scripts pull request #1
Opened 2018-07-23 13:22 UTC by pro100Daim

2018-07-23 13:54 UTC, gyerts requested changes

2018-07-23 13:54 UTC, gyerts commented on king_slave.sh
> +		git checkout slave1/master
при перключение на upstream ветку `slave1/master` ты в состоянии `(detached head at slave1/master)` а тебе нужно создать свою ветку на основе `slave1/master`
```
# 4й параметр (slave1/master) это коммит или ветка на основе которой ты собираешься делать новую ветку (slave1_master)
git checkout -b slave1_master slave1/master 

git branch -a -vv
```

После изменения скрипта, напиши мне ответ под этим сообщением `done with commit q3e34w4w` вместо q3e34w4w нужно подставить реальный коммит

2018-07-23 13:54 UTC, gyerts commented on king_slave.sh
> +                git checkout slave2/master
тоже самое, коммиты нужно делать в ветке а не в состоянии detached head

2018-07-23 14:40 UTC, pro100Daim commented on king_slave.sh
> +		git checkout slave1/master
done with commit 5a84062

после данной модификации, после команды "git checkout -b slave1_master slave1/master" вылетает ошибка:

fatal: 'slave1/master' is not a commit and a branch 'slave1_master' cannot be created from it

2018-07-24 07:50 UTC, pro100Daim commented on king_slave.sh
> +		git checkout slave1/master
done with commit cf43a2f

2018-07-24 08:11 UTC, gyerts commented on king_slave.sh
> +		git clone $BR_LOC/$BARE_REPO_KING
Перемести эту запись за пределы этого блока, так как она не относится к этому блоку и немного путает.
```
cd $WD_LOC
    git clone $BR_LOC/$BARE_REPO_KING

cd $WD_LOC
    git clone $BR_LOC/$BARE_REPO_SLAVE_1
    ...
```

2018-07-24 08:46 UTC, merged